// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASf3NO8jLBGsOymnGxmnxBGY2-xbuXivQ',
    appId: '1:145581671854:web:7f0eaad44b8d732a28743f',
    messagingSenderId: '145581671854',
    projectId: 'art-app-9ce81',
    authDomain: 'art-app-9ce81.firebaseapp.com',
    storageBucket: 'art-app-9ce81.appspot.com',
    measurementId: 'G-J4P8DXE7F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDutepdpyNEoyRNHG4ry-0poCpQO_ePKVM',
    appId: '1:145581671854:android:6163d9c5bae96cc828743f',
    messagingSenderId: '145581671854',
    projectId: 'art-app-9ce81',
    storageBucket: 'art-app-9ce81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmOJEfQJU2zyXrOCuGxVp38oGsYVbwXGw',
    appId: '1:145581671854:ios:584da4c708e6383e28743f',
    messagingSenderId: '145581671854',
    projectId: 'art-app-9ce81',
    storageBucket: 'art-app-9ce81.appspot.com',
    iosClientId: '145581671854-e91th86bb87aj2bhg1qg1sgo9lak4lpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmOJEfQJU2zyXrOCuGxVp38oGsYVbwXGw',
    appId: '1:145581671854:ios:bc88e6a0babb19c828743f',
    messagingSenderId: '145581671854',
    projectId: 'art-app-9ce81',
    storageBucket: 'art-app-9ce81.appspot.com',
    iosClientId: '145581671854-6ku56qag14vbrcatjderisdvduof34c1.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp.RunnerTests',
  );
}
